### ISSUE TITLE
Feature request: Need a way to convert the custom tenhou paipu to this version

### ISSUE THREAD

**Issue by zhengye1** [kobalab/Majiang#101]
Probably similar to te issue #98, and I have this request because Ron2 (which is another one build by JPML) will be closed soon, so the paipu on their end may or maybe lost. That makes me to create the custom tenhou paipu version to save it for my future reference.

However, it only allow do 1 kyoku instead the whole hanchan, which means ... for 1 of the hanchan I saved,  it have 13 kyoku json file, and pretty hard to watch on tenhou side .. (Need to swtich the link for next one instead using their button to switch the kyoku). And thank god this tool it allows me to see the whole hanchan, but the json format is totally different.. therefore it need a way to convert it

**Comment by kobalab** [comment]
私はロン2をプレーしたことがないのですが、
 - ロン2で取得できる牌譜は天鳳のJSON形式(半荘単位ではなく局単位)

ということですね。

#98 でも天鳳のJSON形式の牌譜を電脳麻将形式に変換できないか、というリクエストを受けました。申し訳ないですが、現状対応する予定はありません🙏

新しいロン2は天鳳をベースにしたシステムになるようですので、そうなれば天鳳のXML形式の牌譜がダウンロードできるようになる可能性はありそうです。天鳳のXML形式の牌譜であれば、[@kobalab/tenhou-log](https://github.com/kobalab/tenhou-log)の関数 ```convlog()``` で変換可能です。

```
const convlog = require('@kobalab/tenhou-log');
```
で使用可能です。

**Comment by zhengye1** [comment]
Yes, the new ron2 are tenhou based, however I am afraid that they didn't migrate the existing paipu from the old ron2 into the new one...

**Comment by zhengye1** [comment]
Currently I am working on that using python, however for the hule object, is it possible to hu and fan not calculated if already mangan+ ? I try to modified the json and put into the paifu for check, it becomes.. 
![image](https://user-images.githubusercontent.com/5428784/178356845-03b44930-9085-4e1a-8be1-215e91a7dd0b.png)
not a big deal... but a little bit "ugly"

**Comment by kobalab** [comment]
日本の麻雀のルールでは役満の場合を除き必ず符と翻数を計算します。

<img width="816" alt="スクリーンショット 2022-07-13 1 34 26" src="https://user-images.githubusercontent.com/6400065/178556459-bc30f483-e42e-4bc6-aa4d-a2e97b0b7ea0.png">

https://kobalab.net/majiang/hule.html#m23456p111234s88m1/s7/p9/1/0/1/1/0/0/0/0/0

ですので [牌譜](https://github.com/kobalab/majiang-core/wiki/%E7%89%8C%E8%AD%9C#%E5%92%8C%E4%BA%86) では役満以外の場合 ```fu
``` と ```fanshu``` は省略できません。

**Comment by zhengye1** [comment]
```fanshu``` is not the problem for me, a little problem for me is the ```fu```. But OK, let me figure out the way to calculate that

**Comment by kobalab** [comment]
符は役判定の前に計算する必要があります。なぜなら符がつかない場合、平和になるからです。

https://blog.kobalab.net/entry/20151225/1450970516

**Comment by zhengye1** [comment]
Is it have size limit for upload the json file? here is the file [https://github.com/zhengye1/paipuconverter/blob/master/%E3%82%BB%E3%82%AC%E3%82%B5%E3%83%9F%E3%83%BC%E3%83%95%E3%82%A7%E3%83%8B%E3%83%83%E3%82%AF%E3%82%B9No1_%E6%B1%BA%E5%AE%9A%E6%88%A6.json](url) I convert and I believe it should be correct. However when I try to upload, I got 
![image](https://user-images.githubusercontent.com/5428784/181691023-bea876cf-6d4b-461c-94c3-1e9fdac74401.png)

**Comment by kobalab** [comment]
確かにエラー処理が間違っていますね🙏
次のバージョンで修正します。

**Comment by kobalab** [comment]
牌譜形式が誤っていた場合に出すエラーメッセージは v2.0.0 で修正したのでクローズします。
