### ISSUE TITLE
Can't RON , Can Tsumo

### ISSUE THREAD

**Issue by www01020304** [kobalab/Majiang#104]
![Screenshot_20220823-161957_Firefox](https://user-images.githubusercontent.com/76984709/186097967-c3f740ec-8180-447c-bb3d-1dccd72ec64a.png)
![Screenshot_20220823-162024_Firefox](https://user-images.githubusercontent.com/76984709/186097979-9a39b411-03e7-48d2-8a4f-5cde5bffee81.png)

**Comment by kobalab** [comment]
日本麻雀にはフリテンというルールがあります。
「和了牌を捨てている場合はロン和了できない」というルールです。

上記の手牌の場合、<span style="white-space:pre;"><img src="https://kobalab.github.io/paiga/man1.gif" width="19" height="26" alt="m1"></span> <span style="white-space:pre;"><img src="https://kobalab.github.io/paiga/sou4.gif" width="19" height="26" alt="s4"></span> <span style="white-space:pre;"><img src="https://kobalab.github.io/paiga/sou7.gif" width="19" height="26" alt="s7"></span> が和了牌になりますが、河に <span style="white-space:pre;"><img src="https://kobalab.github.io/paiga/sou7.gif" width="19" height="26" alt="s7"></span> を捨てているのでフリテンとなり、ロン和了できません。

**Comment by www01020304** [comment]
Thank you. I will check it when i meet the "problem "again
