### ISSUE TITLE
機能追加リクエスト: 牌譜の天鳳牌譜エディタの形式での表示・保存

### ISSUE THREAD

**Issue by Apricot-S** [kobalab/Majiang#118]
## 概要

電脳麻将の牌譜を牌譜解析サービス ([NAGA](https://naga.dmv.nico/naga_report/top/), [Mahjong AI Utilities](https://mjai.ekyu.moe/ja.html)) で解析したいと考えています。

解析サービスに入力するため、牌譜を天鳳の牌譜エディタ (https://tenhou.net/6/) で使用されている JSON 形式で表示・保存する機能を追加していただけますでしょうか?

## 類似事例

CityLogs (https://rc.honk.li/)

[麻雀一番街](https://www.mahjong-jp.com/)の牌譜を前述のサービス向けに変換できるサイト

変換例:
<img width="871" alt="CityLogs" src="https://github.com/user-attachments/assets/9f4028e8-397b-499b-80b2-7a65545f6c67">

### NAGA

牌譜入力部:
![カスタム牌譜解析_コピペ用](https://github.com/user-attachments/assets/79967294-7f37-4cc8-afd5-ac11939621ed)

- 「カスタム牌譜解析」機能を使用する
- 天鳳の牌譜ビューア (https://tenhou.net/5/) または牌譜エディタ (https://tenhou.net/6/) の URL 形式で入力する
- 一局ごとに牌譜を分割する必要がある (改行で複数の URL を入力してまとめて解析可能)

牌譜の例:
[output_viewer.example.txt](https://github.com/user-attachments/files/17536028/output_viewer.example.txt)

### Mahjong AI Utilities

牌譜入力部:
![MJAI解析](https://github.com/user-attachments/assets/7b7f0c37-84d3-42b3-9b61-fddca24f62a2)

- 「カスタム牌譜 (tenhou.net/6 JSON)」機能を使用する
- JSON のみを入力する (URL の部分は不要)
- 1 つの JSON 内に複数の局をまとめて入力可能

牌譜の例:
[output_log.example.json](https://github.com/user-attachments/files/17536039/output_log.example.json)

**Comment by Apricot-S** [comment]
電脳麻将形式の牌譜を天鳳形式 (tenhou.net/6 JSON) に変換するツールは作成しました。ご参考までに。

https://github.com/Apricot-S/majiang-log

**Comment by kobalab** [comment]
牌譜エディタを実装したことでこの問題に興味が湧いていたところです。検討したいと思います。

NAGA解析等は使ったことがないのでよくわかっていないのですが、出力はダウンロードよりコピペできるテキスト形式(textareaで表示など)の方が使い勝手がよいでしょうか？

それと出力形式は各局ごとがよいでしょうか？それとも全局まとめた方がよいですか？

**Comment by Apricot-S** [comment]
> NAGA解析等は使ったことがないのでよくわかっていないのですが、出力はダウンロードよりコピペできるテキスト形式(textareaで表示など)の方が使い勝手がよいでしょうか？

コピペできるテキスト形式の方が使いやすいと思います。
ダウンロードしても結局ファイルを開いてコピペが必要です。

また、コピーボタンがあればさらに使いやすいと思います。

> それと出力形式は各局ごとがよいでしょうか？それとも全局まとめた方がよいですか？

全局まとめて出力でよいと思います。
- NAGA 向けの形式 (URL) は 1 行 1 局なので、利用者側で必要分だけ分離するのは簡単です。
- Mahjong AI Utilities は無料で利用でき、1 半荘丸々解析しても大体 10 秒未満で解析が終了するので、局ごとに分離する意味はあまりありません。

出力形式に関しては類似事例としてあげた CityLogs (https://rc.honk.li/) が参考になると思います。
動作確認用に段位戦銀河卓四人半荘戦の牌譜 URL を 1 つ提供します。
「Riichi City log ID」の下のところに牌譜 URL (下記の文字列) を入れて「Submit」を押すと解析サービス向けに変換されたテキストが表示されます。

cl3cu4uai08c5027201g

**Comment by kobalab** [comment]
ver.2.4.2 に天鳳のJSON形式の牌譜データを出力する機能を追加しました。

  - [電脳麻将でNAGA解析用のデータを作成する](https://blog.kobalab.net/entry/2024/11/02/223910)

**Comment by Apricot-S** [comment]
ご対応ありがとうございます。
早速試したのですが、和了時にバグがあります。

和了時に包がないときも起家に「パオ」の表示が出ます。
![スクリーンショット 2024-11-02 225527](https://github.com/user-attachments/assets/16301fa1-e765-42d7-939a-efc4e0f1372f)

おそらく、包がないときは包責者に和了者を指定する必要がありますが、`0` が設定されていることが原因と思われます。
https://github.com/kobalab/tenhou-url-log/blob/9e4e8b9469bae990e409124bdf876222c0538a85/lib/logconv.js#L83-L91

参考: 該当部分の majiang-log での実装
https://github.com/Apricot-S/majiang-log/blob/aa3cbb4c94a319c099c8e1f5190c0a47b2f59fba/src/lib/hule.ts#L225

**Comment by Apricot-S** [comment]
ロンの場合でも、包がないときは包責者に和了者を指定する必要があります。
包責者に放銃者を指定すると添付画像のようになります。

![スクリーンショット 2024-11-02 231312](https://github.com/user-attachments/assets/080db545-2fa1-47eb-a086-a70183181172)

**Comment by kobalab** [comment]
すいません。確認不足でした。
ですが、なぜか私の環境では再現しないのです。発生するのは https://tenhou.net/5/ のビューアでしょうか？
(発生させないことには修正確認もできず困っています)

**Comment by kobalab** [comment]
分かりました！
 https://tenhou.net/6/ を経由して牌譜を再生させると再現しませんね。電脳麻将の出力の /6/ を /5/ に書き換えたら再現しました。こんな罠が……

**Comment by kobalab** [comment]
修正し、ver.2.4.3 としてリリースしました。

電脳麻将の牌譜エディタが明確にパオを指定する方法を持っておらず(点数の移動だけで表す)、パオなしのルールにも対応している現状の仕様からはパオ対象を特定することができないため、「パオ」と表示させないために一律和了者を設定する修正としました。

**Comment by Apricot-S** [comment]
早速の対応ありがとうございます。
パオ発生時のパオ責任者の指定に関しては修正予定はありますか?
もしくは今後別の Issue を立てますか?

修正予定なし or 別 Issue を立てるのであれば本 Issue は close します。

**Comment by kobalab** [comment]
確認ありがとうございます。
パオ責任者に関して修正は考えていません。
問題なければクローズしていただければと思います。

**Comment by Apricot-S** [comment]
パオに関しては

- 天鳳の牌譜エディタも対応していない
- 修正は和了部分の数字を 1 個修正するだけ
- そもそもほとんど出現しない

なので、どうしても修正したければ手動で修正しても問題ないと考えています。
そのため、牌譜エディタでサポートしない方針であればそれでよいと思います。

最後に、この度はリクエストに応えていただきありがとうございました!
