### ISSUE TITLE
Bug in xiangting.js

### ISSUE THREAD

**Issue by CuteEric** [kobalab/Majiang#21]
The algorithm you used to calculate xiangting has a mistake. 
The result is not always the same with the result calculated by http://tenhou.net/2/.
For example, 14668889m.  Your algorithm is inaccurate.

**Comment by kobalab** [comment]
Majiang.Util.xiangting require 13 or 14 tiles.
14668889m has only 8 tiles. It's NOT complete Shoupai.

**Comment by CuteEric** [comment]
What about the other 3*n+2 tiles?

**Comment by kobalab** [comment]
手牌が完全でない場合の向聴数の定義はないです。
- 天鳳
  残りの牌は面子になっていると仮定して向聴数を計算します
- 電脳麻将
  残りの牌はすべて孤立牌と仮定して向聴数を計算します

指摘の件はこの違いに起因します。

**Comment by CuteEric** [comment]
多谢！

**Comment by kobalab** [comment]
不客气😉

**Comment by CuteEric** [comment]
你是中国人啊

**Comment by kobalab** [comment]
不是，我在中国生活的日本人  : )

**Comment by CuteEric** [comment]
天鳳
    残りの牌は面子になっていると仮定して向聴数を計算します
    電脳麻将
    残りの牌はすべて孤立牌と仮定して向聴数を計算します
可以用汉语解释一下么？我用谷歌翻译感觉怪怪的，难理解，多谢

**Comment by kobalab** [comment]
如果手牌不是完全的话，怎么算“向听数”呢？

- 天凤：
   假设另外的都是面子的
- 电脑麻将：
   假设另外的都是孤立的

看得懂吗？

**Comment by CuteEric** [comment]
另外的牌指的是副露牌吧
副露的牌应该是碰了和杠了的牌，应该假设都是面子啊

**Comment by kobalab** [comment]
可能天凤的和我的算向听数的目的不一样。

天凤的目的我也不知道，可是我的目的就是用“麻将AI”的。要假设另外的都是面子的话，麻将AI加了面子就好的。我的算法有“应用性”。

**Comment by kobalab** [comment]
还有，什么是对的不对的，对我来说没意义。只说目的不一样做法也不一样。

**Comment by kobalab** [comment]
为什么我的做法有多“应用性”呢？
看 Majiang.Player.prototype.xiangting() 就明白。

**Comment by CuteEric** [comment]
多谢您耐心的回答，谢谢。

**Comment by kobalab** [comment]
没事😃

**Comment by CuteEric** [comment]
前辈不好意思又打扰你了
有没有专门的论文或者著作介绍怎么计算上听数(向听数)的？我在网上看到的你们日文网页上介绍上听数的计算几乎都不一样，请多多指教，谢谢！

**Comment by kobalab** [comment]
我参考这张网页
http://mahjong.ara.black/etc/shanten/index.htm

**Comment by CuteEric** [comment]
多谢前辈
再请教一个问题(哈哈，我的问题好多)：日本的一人麻将、三人麻将和四人指的是参与人数么？一人麻将就是用于个人使用练习的么？

**Comment by kobalab** [comment]
一二三就是参与人数。
“一人麻将”是练习打麻将的一个电子游戏的名字（不是一般的词语）。
四人麻将就是一般的麻将。
日本还有三人麻将，规则有点不同，有人叫“三麻”(さんま)。天凤上也能玩三人麻将，你试试吧。
