### ISSUE TITLE
人間のPlayerが立直後に大明槓できる

### ISSUE THREAD

**Issue by chinshi** [kobalab/Majiang#26]
立直后却可以明杠。。

**Comment by kobalab** [comment]
以下的条件下立直后也可以明杠：
 1. 听牌没变
 2. 用自摸的牌明杠

[天凤](http://tenhou.net/)也是一样。

**Comment by kobalab** [comment]
不好意思。我看错了你说“暗杠”，你说的对，这是BUG。

**Comment by kobalab** [comment]
大明槓できるか否かの判定(Majiang.Player.prototype.get_gang_mianzi())に「リーチしていないこと」の条件が漏れている。
AIの場合、それより前に「(自分を含め)リーチ者がいる場合は副露しない」という判断をしているため、この事象がたまたま発生しなかった。

**Comment by kobalab** [comment]
v0.9.6に反映。
