### ISSUE TITLE
电脑自动对战模式相关

### ISSUE THREAD

**Issue by aliofwind** [kobalab/Majiang#53]
因为有一些参考模拟对战用来分析的需要，自动对战模式能否添加查看手牌和终局之后保存牌谱的功能

**Comment by kobalab** [comment]
我考虑自动对战时能下载牌谱的功能吧。

**Comment by aliofwind** [comment]
非常感谢

发送自 Windows 10 版邮件应用

发件人: Satoshi Kobayashi
发送时间: 2019年7月15日 19:03
收件人: kobalab/Majiang
抄送: aliofwind; Author
主题: Re: [kobalab/Majiang] 电脑自动对战模式相关 (#53)

我考虑自动对战时能下载牌谱的功能吧。

**Comment by kobalab** [comment]
自動対戦に以下のUIを追加する。
 1. space 押下でゲームを一時停止した時に牌譜ダウンロードボタンを表示する
 2. 一時停止したゲームが終局した時にも牌譜ダウンロードボタンを表示する
 3. 手牌をクリックした時に手牌表示/非表示を切り替える
 4. 河をクリックした時にツモ切り表示/非表示を切り替える

**Comment by kobalab** [comment]
v1.2.0 に反映
