### ISSUE TITLE
请问源码下载后如何运行出demo的效果

### ISSUE THREAD

**Issue by Ethic88** [kobalab/Majiang#54]
各方面都是初心者 请教一下是不是.gitignore用过后 可供下载的源码并不是全部的 所以没法在本地实现demo的效果

**Comment by kobalab** [comment]
電脳麻将はNode.jsアプリなので、ダウンロード後以下の操作が必要です。

$ npm install
$ npm run release

その後、./www/index.html をブラウザで開いてください。

你看得懂吗？

**Comment by Ethic88** [comment]
搞定啦 ありがとうございました！

**Comment by kobalab** [comment]
没事儿！
