### ISSUE TITLE
天鳳牌譜変換ツールJS版実装

### ISSUE THREAD

**Issue by Equim-chan** [kobalab/Majiang#64]
Considering the whole thing is written in JS except the convlog.pl, it would be more convenient if users can just convert the log in their browser instead of requiring them to install Perl with JSON module and run under the command line.

Due to CORS limit, the JS implementation on browser may not be able to download the tenhou log automatically, so maybe we can let them upload or just paste the XML instead, and then convert it into proper JSON format.

**Comment by Equim-chan** [comment]
I have made a simple utility to do this in browser, though, it doesn't look good. I didn't rewrite convlog.pl to JS yet, instead at the moment it uses [Perlito](https://fglock.github.io/Perlito/) to translate from perl to JS which is heavy.

https://gh.ekyu.moe/tenhou-convlog/

**Comment by kobalab** [comment]
提案ありがとうございます。

JavaScript版の convlog.pl は別のリポジトリ https://github.com/kobalab/tenhou-log で開発中です。
実は既にコーディングは完了していて、リモートにPUSHしていない状態です。ただしコーディングスタイルはNode.jsのものなので、ブラウザで動かすには変換が必要かもしれません。(私はサーバサイドで動作させることを意図していました)

もうすぐ中国は春節休みになるので、この機会にPUSHしようと思います。

**Comment by kobalab** [comment]
前回回答で書き忘れましたが、Perl版の convlog.pl を使用した牌譜変換CGIはすでに設置済みです。

牌譜変換のみ
http://kobalab.net/majiang/tenhou-log/2011020417gm-00a9-0000-b67fcaa3.json

牌譜変換して牌譜を再生
http://kobalab.net/majiang/paipu.html?tenhou-log/2011020417gm-00a9-0000-b67fcaa3.json

牌譜変換して牌譜を特定の場所から再生
http://kobalab.net/majiang/paipu.html?tenhou-log/2011020417gm-00a9-0000-b67fcaa3.json#/1/0/3:i

2011020417gm-00a9-0000-b67fcaa3 が牌譜IDです。

**Comment by kobalab** [comment]
本日 v1.0.0 をリリースしました。
https://github.com/kobalab/tenhou-log

npmにも登録しました。
https://www.npmjs.com/package/@kobalab/tenhou-log

**Comment by kobalab** [comment]
使い方をブログに書きました。
- [電脳麻将で天鳳の牌譜を検討する - koba::blog](https://blog.kobalab.net/entry/2020/07/08/080228)
