### ISSUE TITLE
振聽 & Possible unrecoginsed 和了

### ISSUE THREAD

**Issue by edward-martyr** [kobalab/Majiang#67]
**㈠**

I'm quite enjoying this app but encountered this:

<img width="805" alt="Screenshot 2020-05-02 at 10 59 00" src="https://user-images.githubusercontent.com/42882301/80853846-40352900-8c66-11ea-9f53-c30430206b5a.png">

I'm not very familiar with Japanese mahjong (振聽 rules, etc), yet I think this makes a 和了. 

**㈡**

電脳麻雀 would be more playable for Chinese players if there's a way to turn off 振聽.

**Comment by kobalab** [comment]
日本麻雀は役がないと和了できないです。

http://kobalab.net/majiang/hule.html#p11s23345666s4,m4-56/z3//1/0/2//0/0/0/0/0

![名称未設定](https://user-images.githubusercontent.com/6400065/80929462-d4c29700-8dde-11ea-83f0-48a58d9c7662.png)

**Comment by edward-martyr** [comment]
Thank you for your reply. Is there a complete list of all 役s that your programme recognises?

**Comment by kobalab** [comment]
Wikipediaの以下の項目にある「主な役」を採用しています。
- https://ja.wikipedia.org/wiki/%E9%BA%BB%E9%9B%80%E3%81%AE%E5%BD%B9%E4%B8%80%E8%A6%A7

**Comment by edward-martyr** [comment]
I see.
