### ISSUE TITLE
tenhou.net/6 format log import support?

### ISSUE THREAD

**Issue by uf0wxxel** [kobalab/Majiang#98]
Hi,

Thank you for this great project! Do you have any plan to support log (paipu) import with tenhou.net/6 format?

I am requesting this feature because I want to replay logs (of tenhou / mahjong soul) offline. Most of the tools I found (including akochan-reviewer and some other log converting / saving tools) support only tenhou.net/6 format logs. However, I cannot find any tools that replay the logs offline, except for the official online replayer tenhou.net/5. It seems that tenhou.net/5 does not support iframe, the resources need to be reloaded once viewport size is changed, and sometimes the resources are not loading (because of CDN issues), which is inconvenient for analysis. Then, I find that this Majiang project does a good job in log replay, including the UI and features. It already supports log import from tenhou log id, but it does not support tenhou.net/6 format json logs (so the logs exported from mahjong soul by other tools and tenhou logs saved by akochan-reviewer cannot be replayed).

I hope you can support this feature if you have time. Thank you!

**Comment by kobalab** [comment]
電脳麻将(kobalab/Majiang)をご利用いただき、ありがとうございます😊

天鳳(Tenhou)には2つの牌譜形式があります。

 1. XML形式 (天鳳で実際に行われた対戦の結果を保存する形式 → tenhou.net/5)
 2. JSON形式 (天鳳の牌譜エディタが作成する形式 → tenhou.net/6)

XML形式はすでに電脳麻将で再生可能です😎(→ [牌譜生成例](https://kobalab.net/majiang/paipu.html?tenhou-log/2020090420gm-0009-10011-d937e1ff.json:%E7%AC%AC%E5%8D%81%E6%9C%9F%20%E5%A4%A9%E9%B3%B3%E5%90%8D%E4%BA%BA%E6%88%A6%0a%E7%AC%AC%E4%B8%80%E7%AF%80%201%E5%8D%93(1)))

今回の要望は

- 雀魂(Mahjong soul)の牌譜 → 天鳳のJSON形式の牌譜 → 電脳麻将形式の牌譜 

と変換して、雀魂の牌譜を電脳麻将で再生したいということと理解しました。

「天鳳のJSON形式の牌譜 → 電脳麻将形式の牌譜」を実現する計画はないです。「雀魂の牌譜 → 電脳麻将形式の牌譜」が可能なら実現したいですが、雀魂の牌譜の形式や取得方法が非公開なので現段階では実現できません。申し訳ありません🙏

**Comment by majiang** [comment]
仮に変換ロジック部分を私が実装して提供できるとしたら前向きになりえますか?

**Comment by kobalab** [comment]
天鳳のJSON形式の牌譜 → 電脳麻将形式の牌譜
が実現できて電脳麻将形式の牌譜をローカルに保存できれば、ローカルにある牌譜を読み込んで再生する機能はすでに電脳麻将にあるので私としては何もすることはないですね😊

本当は天鳳でやっているように、牌譜IDだけを指定して電脳麻将で再生したいのですが、雀魂は牌譜のダウンロード方法も牌譜形式も非公開なので今は手が出せないです。現状他の方がやっているのはブラウザの拡張機能で「雀魂の牌譜を盗み読み」する方法なので手を出したくないです。

**Comment by majiang** [comment]
ローカル変換できるなら何もすることはない、というところに触れていなかったのは私の頭が悪かったです。

質問の意図は、その場合に生じるユーザ側の変換の手間を取り除くことでした。小さな変更で済みそうで、そこに前向きなら、どのようなインタフェースにしたがえばロード部分に取り込んでもらえるでしょうか?

**Comment by kobalab** [comment]
天鳳のXML形式の牌譜を電脳麻将形式に変換する部分は [@kobalab/tenhou-log](https://github.com/kobalab/tenhou-log) として別パッケージにしています。なので変換部分は外部にしておきたいというのが私の気持ちです。

それと今は [ver.2.0 の作成中](https://blog.kobalab.net/entry/2021/04/26/234352) で全体をリファクタリングしているので、改造はちょっと後回しにしたいという事情もあります。

という訳で天鳳のJSON形式の牌譜を電脳麻将形式に変換する部分を作成いただいても、取り込む気持ちはないです。申し訳ない🙏
(手間を減らすのが目的であれば、雀魂の牌譜を直接電脳麻将形式にするという方法もありますね。もし雀魂の情報が公開されるなら私はその方法をとります)

わからないのは雀魂の牌譜を電脳麻将で再生する需要があるのか？ということです。実はなぜ電脳麻将を使いたいのかがよくわかっていないのです……
(私自身は電脳麻将で牌譜検討したいから使っていますが。あと天鳳の牌譜ビューアよりちょっと使いやすいかな😎)

**Comment by majiang** [comment]
`tenhou-log` までは見ていて、同じインタフェースにしたがえばアリなのかなと想像していました。ちょっと試してみようかと思ったのですが、JSは苦手なので取り込んでもらえる可能性がある場合のみ選択、外部ツールとして別に公開するなら慣れた言語を使おうと思ったのでした。

@uf0wxxel in short: he suggests that someone release a standalone converter, which you can use to satisfy your need.  Maybe I can help you with that.

**Comment by uf0wxxel** [comment]
Thank you for your reply!

I think current solutions for saving Mahjong Soul logs are mostly using Tenhou's JSON format, including a userscript I found (its name is `downloadlogs`) and another (heavier) application (maybe they use similar techniques). I believe the only ways to get Mahjong Soul logs is to simulate websocket requests and parsing them (difficult and requires login/auth), or to use a script to parse the logs in the browser by data processed by the game (much better). Actually, you can get the replay data by `uiscript.UI_Replay.Inst.rounds` when you are reviewing some logs (you can test it in Console of DevTools), but the format conversion is not trivial. (Directly using response data preprocessed by the game through `app.NetAgent.sendReq2Lobby` is also a way.)

@majiang If we have to find a standalone solution, modifying the `downloadlogs` userscript is possible. I will try if I have time. A copy of the script is here: 
[downloadlogs.user.js.txt](https://github.com/kobalab/Majiang/files/8077302/downloadlogs.user.js.txt)


I will close this issue since it is not related to this project.

**Comment by uf0wxxel** [comment]
@majiang I found another solution for my current problem: caching tenhou.net/5 to local. I modified the script (of tenhou.net/5) a bit so that the cached images can be always reused. It works well for me now, so I decide to drop the plan for modifying the `downloadlogs` userscript.
